import { Component, HostListener, OnInit } from '@angular/core';
import { FilterComponent } from "../../shared/filter/filter.component";
import { PaginationComponent } from "../../shared/pagination/pagination.component";
import { CarouselComponent } from "../../shared/carousel/carousel.component";
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  standalone: true,
  imports: [
    CommonModule,
    FilterComponent,
    PaginationComponent,
    CarouselComponent
  ]
})
export class HomeComponent implements OnInit {

  actividades = [
    {
      id: 1,
      deporte: "Fútbol",
      titulo: "Escuela de Fútbol Talento Joven",
      descripcion: "Entrena como los grandes. Clases para niños desde los 5 años.",
      extra: "Opcion de Becas deportivas.",
      imagen: "assets/img/post/futbol1.jpg",
      icono: "assets/icon/futbol.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 2,
      deporte: "Natación",
      titulo: "Academia de Natación AquaKids",
      descripcion: "Aprende a nadar en un entorno seguro con instructores certificados.",
      extra: "",
      imagen: "assets/img/post/natacion1.jpg",
      icono: "assets/icon/natacion.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 3,
      deporte: "Tenis",
      titulo: "Club de Tenis El Bosque",
      descripcion: "Clases para principiantes y niveles intermedios. ¡Saca tu mejor saque!",
      extra: "",
      imagen: "assets/img/post/tenis1.jpg",
      icono: "assets/icon/tenis.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 4,
      deporte: "Basketball",
      titulo: "Basket Kids Santiago",
      descripcion: "Entrenamientos para niños y adolescentes todos los sábados.",
      extra: "",
      imagen: "assets/img/post/basket1.jpg",
      icono: "assets/icon/baloncesto.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 5,
      deporte: "Vóleibol",
      titulo: "Escuela Vóley Activo",
      descripcion: "Formación técnica y juegos en equipo para jóvenes entusiastas del vóley.",
      extra: "",
      imagen: "assets/img/post/voleibol1.jpg",
      icono: "assets/icon/voleibol.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 6,
      deporte: "Atletismo",
      titulo: "Escuela de Atletismo Juvenil",
      descripcion: "Entrenamientos de velocidad, salto y resistencia en pista profesional.",
      extra: "",
      imagen: "assets/img/post/atletismo2.jpg",
      icono: "assets/icon/running.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 7,
      deporte: "Karate",
      titulo: "Karate Dojo Nippon",
      descripcion: "Disciplina, defensa personal y técnicas tradicionales. ¡Primera clase gratis!",
      extra: "",
      imagen: "assets/img/post/karate1.jpg",
      icono: "assets/icon/combate.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 8,
      deporte: "Yoga",
      titulo: "Centro de Yoga Zen",
      descripcion: "Clases para todos los niveles. Mejora tu flexibilidad y bienestar.",
      extra: "",
      imagen: "assets/img/post/yoga1.jpg",
      icono: "assets/icon/yoga.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 9,
      deporte: "Muay Thai",
      titulo: "Escuela de Muay Thai",
      descripcion: "Aprende a luchar con disciplina y respeto. Clases mixtas.",
      extra: "",
      imagen: "assets/img/post/muaythai1.jpg",
      icono: "assets/icon/combate.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 10,
      deporte: "Futbol",
      titulo: "Escuela de Arqueros Profesionales",
      descripcion: "Entrena con los mejores. Clases para todos los niveles.",
      extra: "",
      imagen: "assets/img/post/arqueros1.jpg",
      icono: "assets/icon/futbol.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 11,
      deporte: "Ciclismo",
      titulo: "Club de Ciclismo Juvenil",
      descripcion: "Recorre rutas guiadas y aprende técnicas de ciclismo profesional.",
      extra: "",
      imagen: "assets/img/post/ciclismo1.jpg",
      icono: "assets/icon/bicicleta.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['6 años', '7 años', '8 años', '9 años', '10 años', '11 años', '12 años'],
      edadMin: 6,
      edadMax: 12,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: true,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    },
    {
      id: 12,
      deporte: "Crossfit",
      titulo: "Escuela de Crossfit Total",
      descripcion: "Desarrolla tecnicas de Crossfit profesional.",
      extra: "",
      imagen: "assets/img/post/crossfit1.jpg",
      icono: "assets/icon/crossfit.png",
      region: "Metropolitana",
      comuna: "Las Condes",
      direccion: "Av. Ejemplo 1234",
      telefono: "+56 9 8765 4321",
      email: "contacto@ejemplo.cl",
      representante: "Nombre Representante",
      becaDisponible: true,
      esGratuito: false,
      modalidadPago: "Pago",
      tipoPago: "Mensual",
      precio: 20000,
      diasEjecucion: ['Martes', 'Jueves', 'Sábado'],
      horarios: [{ 'inicio': '16:00', 'fin': '17:30' }, { 'inicio': '17:45', 'fin': '19:15' }],
      edadesPermitidas: ['+18 años'],
      edadMin: 18,
      edadMax: 60,
      sexo: ['Masculino', 'Femenino'],
      aceptaPCD: false,
      cuposDisponibles: 25,
      requiereInscripcionPrevia: true,
      sitioWeb: "https://ejemplo-deporte.cl",
      redesSociales: { 'instagram': 'https://instagram.com/ejemplodeporte', 'facebook': 'https://facebook.com/ejemplodeporte' },
      observaciones: "Traer implementación deportiva personal.",
      nivel: ['Principiante', 'Intermedio'],
      estado: "Abierta",
      materiales: { 'requiere': ['Ropa deportiva', 'Botella de agua'], 'proporcionados': ['Implementos básicos'] },
      fechaInicio: "2024-10-01",
      fechaTermino: "2024-12-20",
      modalidad: "Presencial"
    }
  ];
  loading: boolean = true;
  selectedOrder: any = 'Más relevantes';
  orders = ['Más relevantes', 'Ordenado A-Z', 'Ordenado Z-A', 'Más nuevos', 'Más antiguos'];
  showScrollTopButton = false;
  constructor() { }

  ngOnInit() {
    setTimeout(() => {
      this.loading = false;
    }, 3000);
  }

  currentPage: number = 1;  // Página actual
  totalPages: number = 10;  // Total de páginas
  itemsPerPage: number = 5;  // Elementos por página

  onPageChange(page: number) {
    this.currentPage = page;
    console.log(`Página cambiada a: ${this.currentPage}`);
    // Aquí puedes agregar lógica para cargar los datos de la nueva página
  }

  onFiltrosActualizados(filtros: any) {
    console.log('Filtros actualizados:', filtros);
    this.loading = true;
    setTimeout(() => {
      this.loading = false;
    }, 3000);
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    const actividadCards = document.getElementById('actividad-cards');
    if (actividadCards) {
      const top = actividadCards.getBoundingClientRect().top;
      this.showScrollTopButton = top <= window.innerHeight * 0.9;
    }
  }

  scrollToTop() {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}
